version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '%(levelname)s - %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: kallos_portfolios.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  kallos_portfolios:
    level: INFO
    handlers: [console]
    propagate: false
  
  kallos_portfolios.storage:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  kallos_portfolios.models:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  kallos_portfolios.optimisers:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  kallos_portfolios.backtest:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: WARNING
  handlers: [console]
